### ISSUE TITLE
Fix URL issue with Request Submissions

### ISSUE THREAD

**Issue by rjmajma** [18F/foia-hub#359] opened 2014-12-12 18:35 UTC
The submit page URL ends with an identification number (ex. https://foia.18f.us/request/success/6/). Using this numbering system makes it easy for someone to go in and look back at other submissions. We should fix this.

There are a few ways to fix this. Whoever takes this on should determine how to do that.

**Comment by NoahKunin** [comment] 2015-01-08 15:29
Happy :new: :calendar: all. Thinking this will get into your next sprint?

**Comment by rjmajma** [comment] 2015-01-09 04:00
Assigning to @khandelwal to get done this sprint.

**Comment by rjmajma** [comment] 2015-01-13 16:44
Hey @khandelwal, can we prioritize completion of this task? I don't want to have this be what holds us up.

**Comment by khandelwal** [comment] 2015-01-13 20:44
I'm actually going to remove the request submission piece from the code. It's not something we use now, or plan to in the near future. When we start dealing with requests again, we'll do this properly.

**Comment by NoahKunin** [comment] 2015-01-20 18:35
Hey team - just a reminder that if you reference an issue where you're going to do the work, a merge notification there does not come back to me. When it's actually deployed, you need to come back here so I get pushed a notification, as opposed to wondering where this is at and then finding the time to come back here and read what's up.

Looking very quickly at the site, it appears it hasn't been deployed yet. So before you close this issue, tag me with a notice that it's been deployed and available for re-testing. Or, if you have time and run the test for me and validate, that's always welcome.

**Comment by rjmajma** [comment] 2015-01-20 18:37
Just merged a few hours ago, so it is in the works. Will make sure to @ you here and in any other relevant repos when appropriate. Thanks!

**Comment by NoahKunin** [comment] 2015-01-20 18:41
Sounds great!

**Comment by rjmajma** [comment] 2015-01-20 23:16
This was merged in https://github.com/18F/foia-hub/pull/413 @NoahKunin.

**Comment by NoahKunin** [comment] 2015-01-21 02:02
Re-opening. As I mentioned above, this issue only gets closed when we have evidence the change has made it all the way to production and works as intended. Merging doesn't close this issue. To whit, I just went to the site now and was able to reproduce the issue again. 

Evidence: https://foia.18f.us/request/success/8/

cc @konklone @khandelwal

**Comment by khandelwal** [comment] 2015-01-21 05:24
Looks like it didn't deploy. Our procedure is to close on merge after verification. This was erroneously closed. I will check why it didn't deploy.

**Comment by khandelwal** [comment] 2015-01-21 16:51
ok, we just re-deployed. Here's an image that shows that the request/success URL is no longer valid. 


![screen shot 2015-01-21 at 11 49 43 am](https://cloud.githubusercontent.com/assets/636752/5840467/d0c13aac-a163-11e4-8215-56b1bbf92116.png)

**Comment by khandelwal** [comment] 2015-01-21 16:52
Here's what happens if you can see the form, and hit submit: 

![screen shot 2015-01-21 at 11 51 57 am](https://cloud.githubusercontent.com/assets/636752/5840495/fb20d956-a163-11e4-8c74-ec390c8cd2a3.png)

**Comment by khandelwal** [comment] 2015-01-21 16:53
@NoahKunin Does that suffice for evidence?

**Comment by khandelwal** [comment] 2015-01-21 17:07
This is now closed as per our process.

**Closed** 2015-01-21 17:07 UTC
Labels: ATO, bug

**Comment by NoahKunin** [comment] 2015-01-21 17:31
Awesome, thanks!

On Wednesday, January 21, 2015, Shashank Khandelwal <
notifications@github.com> wrote:

> Closed #359 <https://github.com/18F/foia-hub/issues/359>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/foia-hub/issues/359#event-222455863>.
>


-- 
Noah Kunin
Delivery Architecture + Infrastructure Services Director
202-577-7167 | @18F <https://twitter.com/18F>
